services:
  backend:
    build: ./backend
    container_name: emoji-backend
    # ports:
    #   - "8080:8080"
    environment:
      - REDIS_ADDR=redis:6379
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: emoji-redis
    restart: always
    volumes:
      - redis_data:/data
    command: ["redis-server", "--save", "60", "1", "--appendonly", "yes"]

  frontend:
    build: 
      context: ./frontend
      args:
        - VITE_FORCE_USER_ID=1234567
#    image: nginx:alpine
    container_name: emoji-frontend
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8081:80"
    depends_on:
      - backend

volumes:
  redis_data:
